Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:PolicyJson = @'
{"schemaVersion":1,"purpose":"official-deepseek-harness-desktop-local-build","repository":"https://github.com/deepseek-ai/deepseek-harness.git","tag":"dsh-v0.1.5-rc.2","commit":"fb2c4b9e698e30edb738bca4cf0618587db7d203","tree":"bd7dd6d90010a35d3d6ff9f12c1f6207d5b6fe38","version":"0.1.5-rc.2","packageManager":"pnpm@11.7.0","nodeEngine":"^22.19.0 || >=24.0.0","defaultRegistry":"https://registry.npmjs.org/","prepareSeedRelativePath":"apps/desktop/scripts/prepare-seed.ts","prepareSeedSha256":"2c2050620aa51ae0eabe9e15303c8ceedc08706378c88f2dac4564470201327e","prepareSeedRegistryLiteralCount":2,"sourceDirectory":"source","toolStateDirectory":"tool-state","receiptDirectory":"receipts","officialCommands":{"install":["install","--frozen-lockfile"],"tests":[{"args":["exec","vitest","run","apps/desktop","apps/desktop-host"]}],"build":["run","prepare:desktop"]},"localPackage":{"appId":"local.cloga.dsh-official-source-build","packageName":"dsh-local-build","productName":"DSH Local Build","artifactName":"dsh-local-build-${version}-win-${arch}.${ext}","installerName":"dsh-local-build-0.1.5-rc.2-win-x64.exe","testOrigin":"https://invalid.invalid","command":["exec","electron-builder","--config","<overlay>","--win","--x64","--publish","never"]},"releaseBoundary":{"windowsForceCodeSigning":true,"officialIdentityClaim":false,"updateChannelConfigured":false,"packageCreated":false,"status":"signed-release-unavailable","reason":"The unmodified official Windows package:desktop:dir path requires the vendor EV certificate, SafeNet token, SignTool, key container, and token PIN. This tool does not discover credentials, impersonate the official application identity, configure an update channel, or patch official source."},"localReleaseBoundary":{"officialIdentityClaim":false,"officialSignature":false,"updateChannel":false,"packageCreated":true,"status":"local-build-complete","reason":"Unsigned local package from pinned official source using an external identity/signing/update overlay. Registry routing is the only temporary source deviation; lockfile and integrity verification remain enforced."}}
'@
$script:ArtifactRelativeRoot = 'apps/desktop/.desktop-build/targets/win-x64'

function ConvertTo-CanonicalJson { param($Value) return ($Value | ConvertTo-Json -Depth 40 -Compress) }
function Get-DshOfficialDesktopBuildPolicy { [CmdletBinding()]param() return ($script:PolicyJson | ConvertFrom-Json) }
function Test-DshOfficialDesktopBuildPolicy { [CmdletBinding()]param([Parameter(Mandatory)]$Policy); if ((ConvertTo-CanonicalJson $Policy) -cne (ConvertTo-CanonicalJson (Get-DshOfficialDesktopBuildPolicy))) { throw 'official-desktop-policy-invalid' }; $true }
function Get-NormalizedPath { param([Parameter(Mandatory)][string]$Path) return [IO.Path]::GetFullPath($Path).TrimEnd('\','/') }
function Test-PathAtOrWithin { param([string]$Candidate,[string]$Parent); $c=Get-NormalizedPath $Candidate; $p=Get-NormalizedPath $Parent; $c.Equals($p,[StringComparison]::OrdinalIgnoreCase) -or ($c+'\').StartsWith($p+'\',[StringComparison]::OrdinalIgnoreCase) }
function Assert-NoReparseAncestor { param([string]$Path); $cursor=Get-NormalizedPath $Path; while($cursor){if(Test-Path -LiteralPath $cursor){$item=Get-Item -LiteralPath $cursor -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw 'build-path-reparse-point'}};$parent=Split-Path -Parent $cursor;if(-not$parent-or$parent-ceq$cursor){break};$cursor=$parent} }
function Assert-NoReparseTree {
    param([string]$Path)
    Assert-NoReparseAncestor $Path
    if (Test-Path -LiteralPath $Path) {
        foreach ($item in @(Get-ChildItem -LiteralPath $Path -Force -Recurse)) {
            if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw 'build-path-reparse-point' }
        }
    }
}
function Assert-ManagedBuildTrees {
    param([string]$Root,$Policy,[switch]$IncludeTarget)
    Assert-NoReparseAncestor $Root
    Assert-NoReparseTree (Join-Path $Root $Policy.toolStateDirectory)
    Assert-NoReparseTree (Join-Path $Root $Policy.receiptDirectory)
    Assert-NoReparseAncestor (Join-Path $Root $Policy.sourceDirectory)
    if($IncludeTarget) {
        $target=Join-Path (Join-Path $Root $Policy.sourceDirectory) ($script:ArtifactRelativeRoot.Replace('/','\'))
        Assert-NoReparseTree $target
        foreach($child in @('runtime','seed','packed','package-set','seed-pnpm','artifacts')) { Assert-NoReparseTree (Join-Path $target $child) }
    }
}
function Assert-DshOfficialDesktopBuildRoot {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$BuildRoot,[string]$RepositoryRoot=(Split-Path $PSScriptRoot -Parent))
    if([string]::IsNullOrWhiteSpace($BuildRoot)-or-not[IO.Path]::IsPathRooted($BuildRoot)){throw 'build-root-must-be-absolute'}
    if($BuildRoot.StartsWith('\\')-or$BuildRoot.StartsWith('//')){throw 'build-root-must-be-fixed-local-drive'}
    $root=Get-NormalizedPath $BuildRoot;$driveName=[IO.Path]::GetPathRoot($root).TrimEnd('\').TrimEnd(':');$drive=Get-PSDrive -Name $driveName -PSProvider FileSystem -ErrorAction SilentlyContinue
    if(-not$drive-or$drive.DisplayRoot-or($drive.Root-and$drive.Root.StartsWith('\\'))){throw 'build-root-must-be-fixed-local-drive'}
    try{if([IO.DriveInfo]::new([IO.Path]::GetPathRoot($root)).DriveType-ne[IO.DriveType]::Fixed){throw 'build-root-must-be-fixed-local-drive'}}catch{if($_.Exception.Message-eq'build-root-must-be-fixed-local-drive'){throw};throw 'build-root-must-be-fixed-local-drive'}
    if((Test-PathAtOrWithin $root $RepositoryRoot)-or(Test-PathAtOrWithin $RepositoryRoot $root)){throw 'build-root-must-not-contain-or-be-inside-operations-repository'}
    foreach($cloud in @($env:OneDrive,$env:OneDriveCommercial,$env:OneDriveConsumer,$env:Dropbox,$env:GoogleDrive)){if($cloud-and[IO.Path]::IsPathRooted($cloud)-and(Test-PathAtOrWithin $root $cloud)){throw 'build-root-cloud-synchronized'}}
    if($root-match'(?i)(^|[\\/])(OneDrive(?: - [^\\/]+)?|Dropbox|Google Drive|iCloudDrive)([\\/]|$)'){throw 'build-root-cloud-synchronized'}
    Assert-NoReparseAncestor $root;foreach($child in @('source','tool-state','receipts')){Assert-NoReparseAncestor (Join-Path $root $child)};$root
}
function Assert-DshRegistry { [CmdletBinding()]param([Parameter(Mandatory)][string]$Registry); try{$uri=[Uri]$Registry}catch{throw 'registry-must-be-absolute-https-url'};if(-not$uri.IsAbsoluteUri-or$uri.Scheme-cne'https'-or-not[string]::IsNullOrEmpty($uri.UserInfo)-or-not[string]::IsNullOrEmpty($uri.Query)-or-not[string]::IsNullOrEmpty($uri.Fragment)){throw 'registry-must-be-absolute-https-url-without-credentials-query-or-fragment'};if([string]::IsNullOrWhiteSpace($uri.Host)){throw 'registry-must-be-absolute-https-url'};$uri.AbsoluteUri }
function Initialize-OfficialBuildRoot {
    param([string]$Root,$Policy)
    $existed=Test-Path -LiteralPath $Root
    if(-not$existed){New-Item -ItemType Directory -Path $Root|Out-Null}
    Assert-ManagedBuildTrees $Root $Policy
    if(-not$existed-and@(Get-ChildItem -LiteralPath $Root -Force).Count-ne0){throw 'new-build-root-not-empty'}
}
function Get-OfficialToolPath { param([string]$Name);$c=Get-Command $Name -CommandType Application -ErrorAction SilentlyContinue|Select-Object -First 1;if($c){Get-NormalizedPath $c.Source} }
function New-SafeProcessEnvironment {
    param([hashtable]$Environment)
    $safe=@{}
    if($Environment){foreach($name in $Environment.Keys){$safe[$name]=$Environment[$name]}}
    foreach($name in @('NODE_OPTIONS','NODE_PATH','npm_config_script_shell','GIT_DIR','GIT_WORK_TREE','GIT_INDEX_FILE','GIT_OBJECT_DIRECTORY','GIT_ALTERNATE_OBJECT_DIRECTORIES','GIT_CEILING_DIRECTORIES','GIT_CONFIG_COUNT','GIT_SSH','GIT_SSH_COMMAND','SSH_ASKPASS','GIT_ASKPASS','COREPACK_INTEGRITY_KEYS')){$safe[$name]=$null}
    foreach($name in [Environment]::GetEnvironmentVariables('Process').Keys){if([string]$name-match'^GIT_CONFIG_(?:KEY|VALUE)_\d+$'){$safe[[string]$name]=$null}}
    return $safe
}
function Invoke-OfficialNativeCommand {
    param([string]$FilePath,[string[]]$ArgumentList,[string]$WorkingDirectory,[hashtable]$Environment,[scriptblock]$CommandRunner)
    $Environment=New-SafeProcessEnvironment $Environment
    if($CommandRunner){return (&$CommandRunner $FilePath ([string[]]$ArgumentList) $WorkingDirectory $Environment)}
    $saved=@{};if($Environment){foreach($name in $Environment.Keys){$saved[$name]=[Environment]::GetEnvironmentVariable($name,'Process');$value=$Environment[$name];if($null-eq$value){Remove-Item -LiteralPath ("Env:"+$name) -ErrorAction SilentlyContinue}else{Set-Item -LiteralPath ("Env:"+$name) -Value ([string]$value)}}}
    try{Push-Location $WorkingDirectory;try{$output=@(&$FilePath @ArgumentList 2>&1|ForEach-Object{$_.ToString()});$exit=$LASTEXITCODE}finally{Pop-Location}}finally{if($Environment){foreach($name in $Environment.Keys){if($null-eq$saved[$name]){Remove-Item -LiteralPath ("Env:"+$name) -ErrorAction SilentlyContinue}else{Set-Item -LiteralPath ("Env:"+$name) -Value $saved[$name]}}}};[pscustomobject]@{exitCode=$exit;output=$output}
}
function Invoke-OfficialCheckedCommand { param([string]$Name,[string]$FilePath,[string[]]$ArgumentList,[string]$WorkingDirectory,[hashtable]$Environment,[scriptblock]$CommandRunner);$started=[DateTime]::UtcNow;$result=Invoke-OfficialNativeCommand $FilePath $ArgumentList $WorkingDirectory $Environment $CommandRunner;if($null-eq$result-or$null-eq$result.exitCode){throw 'command-runner-returned-no-exit-code'};$record=[pscustomobject]@{name=$Name;executable=(Get-NormalizedPath $FilePath);workingDirectory=(Get-NormalizedPath $WorkingDirectory);arguments=@($ArgumentList);startedUtc=$started.ToString('o');durationMilliseconds=[int]([DateTime]::UtcNow-$started).TotalMilliseconds;exitCode=[int]$result.exitCode};if($record.exitCode-ne0){throw "command-failed:${Name}:$($record.exitCode)"};[pscustomobject]@{record=$record;output=@($result.output)} }
function Invoke-OfficialGit { param([string]$Name,[string]$GitPath,[string[]]$Arguments,[string]$WorkingDirectory,[hashtable]$Environment,[scriptblock]$CommandRunner,[switch]$AllowExitOne);$args=@('-c','core.hooksPath=NUL')+$Arguments;$result=Invoke-OfficialNativeCommand $GitPath $args $WorkingDirectory $Environment $CommandRunner;if($AllowExitOne-and$result.exitCode-eq1){return [pscustomobject]@{record=$null;output=@($result.output);exitCode=1}};if($result.exitCode-ne0){throw "command-failed:${Name}:$($result.exitCode)"};[pscustomobject]@{record=[pscustomobject]@{name=$Name;executable=(Get-NormalizedPath $GitPath);arguments=$args;startedUtc=$null;durationMilliseconds=0;exitCode=0};output=@($result.output);exitCode=0} }
function New-IsolatedEnvironment {
    param([string]$Root)
    $state=Join-Path $Root 'tool-state';$home=Join-Path $state 'home';$config=Join-Path $state 'config';$temp=Join-Path $state 'temp'
    $paths=@($state,$home,$config,$temp,(Join-Path $state 'appdata'),(Join-Path $state 'localappdata'),(Join-Path $state 'corepack'),(Join-Path $state 'pnpm-home'),(Join-Path $state 'pnpm-store'),(Join-Path $state 'npm-cache'),(Join-Path $state 'cache'),(Join-Path $state 'state'),(Join-Path $Root 'isolated-dsh-home'))
    foreach($p in $paths){Assert-NoReparseTree $p;if(-not(Test-Path -LiteralPath $p)){New-Item -ItemType Directory $p -Force|Out-Null};Assert-NoReparseTree $p}
    $npmrc=Join-Path $config 'empty.npmrc';if(-not(Test-Path -LiteralPath $npmrc)){New-Item -ItemType File $npmrc|Out-Null}
    return New-SafeProcessEnvironment @{DSH_HOME=(Join-Path $Root 'isolated-dsh-home');HOME=$home;USERPROFILE=$home;APPDATA=(Join-Path $state 'appdata');LOCALAPPDATA=(Join-Path $state 'localappdata');COREPACK_ENABLE_PROJECT_SPEC='0';COREPACK_HOME=(Join-Path $state 'corepack');PNPM_HOME=(Join-Path $state 'pnpm-home');npm_config_cache=(Join-Path $state 'npm-cache');npm_config_store_dir=(Join-Path $state 'pnpm-store');npm_config_userconfig=$npmrc;npm_config_globalconfig=$npmrc;XDG_CONFIG_HOME=$config;XDG_STATE_HOME=(Join-Path $state 'state');XDG_CACHE_HOME=(Join-Path $state 'cache');TEMP=$temp;TMP=$temp;GIT_CONFIG_NOSYSTEM='1';GIT_CONFIG_GLOBAL='NUL';CI='true'}
}
function Test-OfficialNodeVersion { param([string]$Version);$m=[regex]::Match($Version,'^v?(\d+)\.(\d+)\.(\d+)$');if(-not$m.Success){return $false};$a=[int]$m.Groups[1].Value;$b=[int]$m.Groups[2].Value;$c=[int]$m.Groups[3].Value;($a-eq22-and($b-gt19-or($b-eq19-and$c-ge0)))-or$a-ge24 }
function Get-OfficialManifestFacts { param([string]$SourceRoot);$r=Get-Content (Join-Path $SourceRoot 'package.json') -Raw|ConvertFrom-Json;$d=Get-Content (Join-Path $SourceRoot 'apps\desktop\package.json') -Raw|ConvertFrom-Json;$h=Get-Content (Join-Path $SourceRoot 'apps\desktop-host\package.json') -Raw|ConvertFrom-Json;[pscustomobject]@{version=$r.version;desktopVersion=$d.version;desktopHostVersion=$h.version;packageManager=$r.packageManager;nodeEngine=$r.engines.node} }
function Assert-OfficialManifestFacts {param($Facts,$Policy);foreach($n in @('version','desktopVersion','desktopHostVersion')){if($Facts.$n-cne$Policy.version){throw "manifest-version-mismatch:$n"}};if($Facts.packageManager-cne$Policy.packageManager){throw 'package-manager-mismatch'};if($Facts.nodeEngine-cne$Policy.nodeEngine){throw 'node-engine-mismatch'} }
function Assert-OfficialSourceRepository { param([string]$SourceRoot,[string]$GitPath,$Policy,[hashtable]$Environment,[scriptblock]$CommandRunner);$top=(Invoke-OfficialGit source-worktree $GitPath @('rev-parse','--show-toplevel') $SourceRoot $Environment $CommandRunner).output[-1].Trim();$gitDir=(Invoke-OfficialGit source-git-dir $GitPath @('rev-parse','--absolute-git-dir') $SourceRoot $Environment $CommandRunner).output[-1].Trim();if((Get-NormalizedPath $top)-cne(Get-NormalizedPath $SourceRoot)){throw 'official-source-worktree-mismatch'};if(-not(Test-PathAtOrWithin $gitDir $SourceRoot)){throw 'official-source-git-dir-outside-source'};Assert-NoReparseAncestor $gitDir;$origin=(Invoke-OfficialGit source-origin $GitPath @('remote','get-url','origin') $SourceRoot $Environment $CommandRunner).output[-1].Trim();if($origin-cne$Policy.repository){throw 'official-source-origin-mismatch'};$hooks=Invoke-OfficialNativeCommand $GitPath @('config','--local','--get','core.hooksPath') $SourceRoot $Environment $CommandRunner;if($hooks.exitCode-notin@(0,1)){throw 'command-failed:source-hooks-path'};if($hooks.exitCode-eq0-and@($hooks.output|Where-Object{$_-and$_.Trim()}).Count){throw 'official-source-hooks-path-configured'};$hookDir=Join-Path $gitDir hooks;if(Test-Path $hookDir){if(@(Get-ChildItem $hookDir -File -Force|Where-Object{$_.Name-notlike'*.sample'}).Count){throw 'official-source-custom-hook-present'}} }
function Get-OfficialSourceIdentity { param([string]$SourceRoot,[string]$GitPath,[hashtable]$Environment,[scriptblock]$CommandRunner);$commit=(Invoke-OfficialGit source-commit $GitPath @('rev-parse','HEAD') $SourceRoot $Environment $CommandRunner).output[-1].Trim();$tree=(Invoke-OfficialGit source-tree $GitPath @('rev-parse','HEAD^{tree}') $SourceRoot $Environment $CommandRunner).output[-1].Trim();$status=@((Invoke-OfficialGit source-status $GitPath @('status','--porcelain=v1','--untracked-files=all') $SourceRoot $Environment $CommandRunner).output|Where-Object{$_-ne''});[pscustomobject]@{commit=$commit;tree=$tree;clean=$status.Count-eq0;changes=$status} }
function Assert-OfficialSourceState { param([string]$SourceRoot,[string]$GitPath,$Policy,[hashtable]$Environment,[scriptblock]$CommandRunner,[string]$ExpectedLockHash);Assert-OfficialSourceRepository $SourceRoot $GitPath $Policy $Environment $CommandRunner;$i=Get-OfficialSourceIdentity $SourceRoot $GitPath $Environment $CommandRunner;if($i.commit-cne$Policy.commit){throw 'official-source-commit-mismatch'};if($i.tree-cne$Policy.tree){throw 'official-source-tree-mismatch'};if(-not$i.clean){throw 'official-source-dirty'};$lock=(Get-FileHash (Join-Path $SourceRoot 'pnpm-lock.yaml') -Algorithm SHA256).Hash.ToLowerInvariant();if($ExpectedLockHash-and$lock-cne$ExpectedLockHash){throw 'official-lockfile-drift'};[pscustomobject]@{identity=$i;lockHash=$lock} }
function Get-OfficialArtifactInventory { param([string]$SourceRoot);$target=Get-NormalizedPath(Join-Path $SourceRoot ($script:ArtifactRelativeRoot.Replace('/','\')));if(-not(Test-Path $target)){return @()};Assert-NoReparseTree $target;@(Get-ChildItem $target -File -Recurse|Sort-Object FullName|ForEach-Object{$p=Get-NormalizedPath $_.FullName;if(-not(Test-PathAtOrWithin $p $target)){throw 'artifact-path-outside-target'};[pscustomobject]@{path=$p.Substring((Get-NormalizedPath $SourceRoot).Length).TrimStart('\').Replace('\','/');size=$_.Length;sha256=(Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}}) }
function Get-TreeHash { param([string]$Path);$root=Get-NormalizedPath $Path;Assert-NoReparseTree $root;$rows=@(Get-ChildItem $root -File -Recurse|Sort-Object FullName|ForEach-Object{[pscustomobject]@{path=(Get-NormalizedPath $_.FullName).Substring($root.Length).TrimStart('\').Replace('\','/');size=$_.Length;sha256=(Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}});$bytes=[Text.Encoding]::UTF8.GetBytes((ConvertTo-CanonicalJson $rows));$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()} }
function Get-ReceiptPayloadHash {param($Receipt);$copy=[ordered]@{};foreach($p in $Receipt.PSObject.Properties){if($p.Name-cne'receiptSha256'){$copy[$p.Name]=$p.Value}};$bytes=[Text.Encoding]::UTF8.GetBytes((ConvertTo-CanonicalJson $copy));$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()} }
function Write-DshOfficialDesktopBuildReceipt { [CmdletBinding()]param([Parameter(Mandatory)]$Receipt,[Parameter(Mandatory)][string]$Path);if(Test-Path $Path){throw 'receipt-already-exists'};$normalized=$Receipt|ConvertTo-Json -Depth 40|ConvertFrom-Json;$normalized|Add-Member receiptSha256 (Get-ReceiptPayloadHash $normalized);$parent=Split-Path -Parent $Path;if(-not(Test-Path $parent)){New-Item -ItemType Directory $parent|Out-Null};Assert-NoReparseAncestor $parent;$normalized|ConvertTo-Json -Depth 40|Set-Content $Path -Encoding UTF8 -NoNewline;$normalized }
function Test-ExactKeys {param($Object,[string[]]$Names);(ConvertTo-CanonicalJson @($Object.PSObject.Properties.Name|Sort-Object))-ceq(ConvertTo-CanonicalJson @($Names|Sort-Object))}
function Get-LocalOverlayContent {
    param([string]$SourceRoot,$Policy)
    $absolute=Get-NormalizedPath (Join-Path $SourceRoot 'apps\desktop\electron-builder.config.mjs')
    $uri=[Uri]::new($absolute).AbsoluteUri
    if(-not$uri.StartsWith('file:',[StringComparison]::OrdinalIgnoreCase)){throw 'local-overlay-import-not-file-uri'}
    $importLiteral=ConvertTo-Json $uri -Compress
    $text=@"
import upstream from $importLiteral

export default {
  ...upstream,
  appId: '$($Policy.localPackage.appId)',
  productName: '$($Policy.localPackage.productName)',
  extraMetadata: {
    ...upstream.extraMetadata,
    name: '$($Policy.localPackage.packageName)',
    productName: '$($Policy.localPackage.productName)',
  },
  artifactName: '$($Policy.localPackage.artifactName)',
  publish: null,
  win: {
    ...upstream.win,
    forceCodeSigning: false,
    signtoolOptions: undefined,
  },
}
"@
    return $text.Replace("`r`n","`n")
}
function New-LocalOverlay {
    param([string]$Root,[string]$SourceRoot,$Policy)
    $parent=Get-NormalizedPath (Join-Path $Root $Policy.toolStateDirectory)
    Assert-NoReparseTree $parent
    $path=Get-NormalizedPath (Join-Path $parent 'local-electron-builder.config.mjs')
    if(-not(Test-PathAtOrWithin $path $parent)){throw 'local-overlay-path-outside-tool-state'}
    $text=Get-LocalOverlayContent $SourceRoot $Policy
    [IO.File]::WriteAllText($path,$text,[Text.UTF8Encoding]::new($false))
    return [pscustomobject]@{path=$path;sha256=(Get-FileHash $path -Algorithm SHA256).Hash.ToLowerInvariant()}
}
function Assert-PrepareSeedRegistrySource { [CmdletBinding()]param([Parameter(Mandatory)][string]$Path,[Parameter(Mandatory)][string]$ExpectedSha256,[Parameter(Mandatory)][int]$ExpectedCount,[string]$Literal='https://registry.npmjs.org/');$hash=(Get-FileHash $Path -Algorithm SHA256).Hash.ToLowerInvariant();if($hash-cne$ExpectedSha256){throw 'prepare-seed-original-hash-mismatch'};$text=[Text.Encoding]::UTF8.GetString([IO.File]::ReadAllBytes($Path));$count=([regex]::Matches($text,[regex]::Escape($Literal))).Count;if($count-ne$ExpectedCount){throw 'prepare-seed-registry-literal-count-mismatch'};[pscustomobject]@{sha256=$hash;literalCount=$count;text=$text} }
function Invoke-PreparedDesktopBuild { param([string]$Source,[string]$Root,$Policy,$Check,[hashtable]$Environment,[scriptblock]$CommandRunner,[string]$Registry,[Collections.Generic.List[object]]$Commands,[string]$InitialLock);Assert-ManagedBuildTrees $Root $Policy -IncludeTarget;$pnpmVersion=$Policy.packageManager.Split('@')[-1];foreach($tc in @($Policy.officialCommands.tests)){$test=Invoke-OfficialCheckedCommand official-desktop-test $Check.tools.corepack (@(('pnpm@'+$pnpmVersion))+@($tc.args)) $Source $Environment $CommandRunner;$Commands.Add($test.record);Assert-OfficialSourceState $Source $Check.tools.git $Policy $Environment $CommandRunner $InitialLock|Out-Null};$seed=Join-Path $Source ($Policy.prepareSeedRelativePath.Replace('/','\'));$official=$Policy.defaultRegistry;$routing=[ordered]@{registry=$Registry;deviation=$Registry-cne$official;sourcePath=$Policy.prepareSeedRelativePath;originalSha256=$Policy.prepareSeedSha256;literalCount=$Policy.prepareSeedRegistryLiteralCount;patchedSha256=$null;restored=$true;lockAndIntegrityRetained=$true};$originalBytes=$null;$patched=$false
    if($routing.deviation){$checked=Assert-PrepareSeedRegistrySource $seed $Policy.prepareSeedSha256 $Policy.prepareSeedRegistryLiteralCount $official;$originalBytes=[IO.File]::ReadAllBytes($seed);$text=$checked.text;$replacement=$Registry.TrimEnd('/')+'/';$patchedText=$text.Replace($official,$replacement);[IO.File]::WriteAllText($seed,$patchedText,[Text.UTF8Encoding]::new($false));$routing.patchedSha256=(Get-FileHash $seed -Algorithm SHA256).Hash.ToLowerInvariant();$patched=$true}
    $failure=$null;try{$build=Invoke-OfficialCheckedCommand official-desktop-prepare $Check.tools.corepack (@(('pnpm@'+$pnpmVersion))+@($Policy.officialCommands.build)) $Source $Environment $CommandRunner;$Commands.Add($build.record)}catch{$failure=$_}finally{if($patched){[IO.File]::WriteAllBytes($seed,$originalBytes);$routing.restored=((Get-FileHash $seed -Algorithm SHA256).Hash.ToLowerInvariant()-ceq$Policy.prepareSeedSha256);if(-not$routing.restored){throw 'prepare-seed-restore-failed'}};Assert-OfficialSourceState $Source $Check.tools.git $Policy $Environment $CommandRunner $InitialLock|Out-Null};if($failure){throw $failure};[pscustomobject]$routing }
function Get-LocalExecutableVersionInfo { param([string]$Path);return (Get-Item -LiteralPath $Path).VersionInfo }
function Get-LocalPackageEvidence { param([string]$Source,[string]$Root,$Policy,[string]$OverlayPath);$target=Join-Path $Source ($script:ArtifactRelativeRoot.Replace('/','\'));Assert-NoReparseTree $target;$artifacts=Join-Path $target 'artifacts';$installer=Join-Path $artifacts $Policy.localPackage.installerName;$unpacked=Join-Path $artifacts 'win-unpacked';$exe=Join-Path $unpacked ($Policy.localPackage.productName+'.exe');$asar=Join-Path $unpacked 'resources\app.asar';$release=Join-Path $target 'seed\desktop-release.json';$runtime=Join-Path $target 'runtime\versions.json';foreach($p in @($installer,$exe,$asar,$release,$runtime,$OverlayPath)){if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw('local-package-artifact-missing:'+($p|Split-Path -Leaf))}};$expectedOverlay=Get-NormalizedPath (Join-Path (Join-Path $Root $Policy.toolStateDirectory) 'local-electron-builder.config.mjs');if((Get-NormalizedPath $OverlayPath)-cne$expectedOverlay-or-not(Test-PathAtOrWithin $expectedOverlay (Join-Path $Root $Policy.toolStateDirectory))){throw 'local-overlay-path-mismatch'};Assert-NoReparseTree (Split-Path -Parent $expectedOverlay);if([IO.File]::ReadAllText($expectedOverlay)-cne(Get-LocalOverlayContent $Source $Policy)){throw 'local-overlay-content-mismatch'};$rel=Get-Content $release -Raw|ConvertFrom-Json;$run=Get-Content $runtime -Raw|ConvertFrom-Json;if($rel.version-cne$Policy.version-or$rel.hostProtocolVersion-ne3-or$rel.nodeVersion-cne'24.17.0'-or$rel.pnpmVersion-cne'11.7.0'-or$run.node-cne'24.17.0'-or$run.pnpm-cne'11.7.0'){throw 'local-package-seed-version-mismatch'};if(Test-Path (Join-Path $unpacked 'resources\app-update.yml')){throw 'local-package-update-config-present'};$installerSig=(Get-AuthenticodeSignature $installer).Status.ToString();$exeSig=(Get-AuthenticodeSignature $exe).Status.ToString();if($installerSig-cne'NotSigned'-or$exeSig-cne'NotSigned'){throw 'local-package-unexpected-signature'};$versionInfo=Get-LocalExecutableVersionInfo $exe;foreach($value in @($versionInfo.ProductName,$versionInfo.FileDescription,$versionInfo.InternalName)){if($value-cne$Policy.localPackage.productName){throw 'local-package-version-info-identity-mismatch'}};[pscustomobject]@{overlayPath=(Get-NormalizedPath $OverlayPath);installerPath=(Get-NormalizedPath $installer);installerSignature=$installerSig;executablePath=(Get-NormalizedPath $exe);executableSignature=$exeSig;appUpdatePresent=$false;identity=[pscustomobject]@{appId=$Policy.localPackage.appId;packageName=$Policy.localPackage.packageName;productName=$Policy.localPackage.productName};seed=$rel;hashes=[pscustomobject]@{installer=(Get-FileHash $installer -Algorithm SHA256).Hash.ToLowerInvariant();appAsar=(Get-FileHash $asar -Algorithm SHA256).Hash.ToLowerInvariant();executable=(Get-FileHash $exe -Algorithm SHA256).Hash.ToLowerInvariant();seed=(Get-TreeHash (Join-Path $target 'seed'));overlay=(Get-FileHash $OverlayPath -Algorithm SHA256).Hash.ToLowerInvariant()}} }
function Test-DshOfficialDesktopBuildReceipt {
 [CmdletBinding()]param([Parameter(Mandatory)][string]$Path,[Parameter(Mandatory)][string]$SourceRoot,$Policy=(Get-DshOfficialDesktopBuildPolicy),[string]$GitPath=(Get-OfficialToolPath git),[string]$NodeVersion,[string]$PnpmVersion='11.7.0',[scriptblock]$CommandRunner)
 try {
  $r=Get-Content $Path -Raw|ConvertFrom-Json
  $topKeys=@('schemaVersion','action','status','createdUtc','source','tools','commands','artifacts','validation','releaseBoundary','receiptSha256')
  if($r.action-ceq'build'){$topKeys+='registryRouting'}
  if($r.action-ceq'packagelocal'){$topKeys+=@('registryRouting','localPackage')}
  if(-not(Test-ExactKeys $r $topKeys)){throw 'schema-keys'}
  if((Get-ReceiptPayloadHash $r)-cne$r.receiptSha256){throw 'self-hash'}
  if($r.schemaVersion-ne1-or$r.action-cnotin@('prepare','build','packagelocal')-or$r.status-cne'complete'){throw 'schema-values'}
  if(-not(Test-ExactKeys $r.source @('repository','tag','commit','tree','clean','lockfileSha256'))-or-not(Test-ExactKeys $r.tools @('nodeVersion','packageManager','pnpmVersion'))-or-not(Test-ExactKeys $r.validation @('launchedGui','installedDesktop','trackedSourceModified','isolatedDshHome'))){throw 'nested-schema-keys'}
  $root=Split-Path -Parent (Get-NormalizedPath $SourceRoot)
  Assert-ManagedBuildTrees $root $Policy -IncludeTarget
  if((Get-NormalizedPath $r.validation.isolatedDshHome)-cne(Get-NormalizedPath (Join-Path $root 'isolated-dsh-home'))){throw 'isolated-home-path'}
  $state=Assert-OfficialSourceState $SourceRoot $GitPath $Policy $null $CommandRunner
  if($r.source.repository-cne$Policy.repository-or$r.source.tag-cne$Policy.tag-or$r.source.commit-cne$Policy.commit-or$r.source.tree-cne$Policy.tree-or$r.source.clean-ne$true-or$r.source.lockfileSha256-cne$state.lockHash){throw 'source-fields'}
  if($r.tools.packageManager-cne$Policy.packageManager-or$r.tools.pnpmVersion-cne$PnpmVersion-or($NodeVersion-and$r.tools.nodeVersion-cne$NodeVersion)){throw 'tool-fields'}
  $expected=if($r.action-ceq'prepare'){@('pnpm-version','frozen-install')}elseif($r.action-ceq'build'){@('pnpm-version','frozen-install','official-desktop-test','official-desktop-prepare')}else{@('pnpm-version','frozen-install','official-desktop-test','official-desktop-prepare','local-electron-builder')}
  $actualNames=@($r.commands|ForEach-Object{$_.name});if((ConvertTo-CanonicalJson $actualNames)-cne(ConvertTo-CanonicalJson $expected)){throw ('command-order:'+($actualNames-join','))}
  $corepack=Get-OfficialToolPath corepack
  foreach($c in @($r.commands)){
   if(-not(Test-ExactKeys $c @('name','executable','workingDirectory','arguments','startedUtc','durationMilliseconds','exitCode'))-or$c.exitCode-ne0-or-not[IO.Path]::IsPathRooted($c.executable)){throw 'command-shape'}
   if((Get-NormalizedPath $c.executable)-cne(Get-NormalizedPath $corepack)){throw 'command-executable'}
   $expectedWorkingDirectory=if($c.name-ceq'local-electron-builder'){Get-NormalizedPath (Join-Path $SourceRoot 'apps\desktop')}else{Get-NormalizedPath $SourceRoot}
   if((Get-NormalizedPath $c.workingDirectory)-cne$expectedWorkingDirectory){throw 'command-working-directory'}
   $expectedArgs=switch($c.name){'pnpm-version'{@(('pnpm@'+$PnpmVersion),'--version')}'frozen-install'{@(('pnpm@'+$PnpmVersion))+@($Policy.officialCommands.install)}'official-desktop-test'{@(('pnpm@'+$PnpmVersion))+@($Policy.officialCommands.tests[0].args)}'official-desktop-prepare'{@(('pnpm@'+$PnpmVersion))+@($Policy.officialCommands.build)}'local-electron-builder'{@(('pnpm@'+$PnpmVersion),'exec','electron-builder','--config',$r.localPackage.overlayPath,'--win','--x64','--publish','never')}}
   if((ConvertTo-CanonicalJson @($c.arguments))-cne(ConvertTo-CanonicalJson $expectedArgs)){throw 'command-order'}
  }
  if($r.validation.launchedGui-ne$false-or$r.validation.installedDesktop-ne$false-or$r.validation.trackedSourceModified-ne$false){throw 'command-order'}
  foreach($a in @($r.artifacts)){if(-not(Test-ExactKeys $a @('path','size','sha256'))-or$a.path.StartsWith('/')-or$a.path.Contains('..')-or-not$a.path.StartsWith($script:ArtifactRelativeRoot+'/',[StringComparison]::Ordinal)){throw 'command-order'}}
  if((ConvertTo-CanonicalJson @($r.artifacts))-cne(ConvertTo-CanonicalJson @(Get-OfficialArtifactInventory $SourceRoot))){throw 'command-order'}
  if($r.action-cin@('build','packagelocal')){if(-not(Test-ExactKeys $r.registryRouting @('registry','deviation','sourcePath','originalSha256','literalCount','patchedSha256','restored','lockAndIntegrityRetained'))-or$r.registryRouting.restored-ne$true-or$r.registryRouting.literalCount-ne2-or$r.registryRouting.originalSha256-cne$Policy.prepareSeedSha256-or$r.registryRouting.lockAndIntegrityRetained-ne$true){throw 'command-order'};Assert-DshRegistry $r.registryRouting.registry|Out-Null;if(($r.registryRouting.registry-cne$Policy.defaultRegistry)-ne[bool]$r.registryRouting.deviation){throw 'command-order'}}
  if($r.action-ceq'packagelocal'){if((ConvertTo-CanonicalJson $r.releaseBoundary)-cne(ConvertTo-CanonicalJson $Policy.localReleaseBoundary)){throw 'command-order'};$e=Get-LocalPackageEvidence $SourceRoot $root $Policy $r.localPackage.overlayPath;if((ConvertTo-CanonicalJson $e)-cne(ConvertTo-CanonicalJson $r.localPackage)){throw 'command-order'}}elseif((ConvertTo-CanonicalJson $r.releaseBoundary)-cne(ConvertTo-CanonicalJson $Policy.releaseBoundary)){throw 'command-order'}
  $true
 } catch {$script:LastReceiptValidationError=$_.Exception.Message;Write-Verbose("receipt-invalid: "+$_.Exception.Message);$false}
}
function Get-DshOfficialDesktopBuildCheck { [CmdletBinding()]param([string]$BuildRoot='C:\tmp\dsh-official-desktop-build\work',[scriptblock]$CommandRunner,$Policy=(Get-DshOfficialDesktopBuildPolicy),[string]$Registry='https://registry.npmjs.org/');Test-DshOfficialDesktopBuildPolicy $Policy|Out-Null;$registryValue=Assert-DshRegistry $Registry;$root=Assert-DshOfficialDesktopBuildRoot $BuildRoot;$git=Get-OfficialToolPath git;$node=Get-OfficialToolPath node;$corepack=Get-OfficialToolPath corepack;$reasons=[Collections.Generic.List[string]]::new();if(-not$git){$reasons.Add('git-unavailable')};if(-not$node){$reasons.Add('node-unavailable')};if(-not$corepack){$reasons.Add('corepack-unavailable')};$cwd=Split-Path $PSScriptRoot -Parent;$gitEnv=@{GIT_CONFIG_NOSYSTEM='1';GIT_CONFIG_GLOBAL='NUL'};$nodeVersion=$null;if($node){$nodeVersion=(Invoke-OfficialCheckedCommand node-version $node @('--version') $cwd $null $CommandRunner).output[-1].Trim();if(-not(Test-OfficialNodeVersion $nodeVersion)){$reasons.Add('node-engine-mismatch')}};$remoteCommit=$null;if($git){$o=Invoke-OfficialGit official-tag $git @('ls-remote','--refs',$Policy.repository,('refs/tags/'+$Policy.tag)) $cwd $gitEnv $CommandRunner;$line=@($o.output|Where-Object{$_-match'^[0-9a-f]{40}\s+'});if($line.Count-ne1){$reasons.Add('official-tag-unresolved')}else{$remoteCommit=($line[0]-split'\s+')[0];if($remoteCommit-cne$Policy.commit){$reasons.Add('official-tag-commit-mismatch')}}};$community=Join-Path $env:APPDATA 'io.github.hairyf.deepseek-harness-desktop';[pscustomobject]@{schemaVersion=1;action='check';status=$(if($reasons.Count){'blocked'}else{'ready'});reasons=@($reasons);buildRoot=$root;registry=$registryValue;policy=[pscustomobject]@{repository=$Policy.repository;tag=$Policy.tag;commit=$Policy.commit;tree=$Policy.tree};tools=[pscustomobject]@{git=$git;node=$node;corepack=$corepack;nodeVersion=$nodeVersion;requiredPnpm=$Policy.packageManager};officialRef=[pscustomobject]@{resolvedCommit=$remoteCommit;verified=$remoteCommit-ceq$Policy.commit};currentFacts=[pscustomobject]@{communityDesktopDataPresent=[bool](Test-Path $community);liveDataReadOnly=$true;liveProcessesInspected=$false;liveDataModified=$false};releaseBoundary=$Policy.releaseBoundary} }
function Invoke-DshOfficialDesktopBuild {
 [CmdletBinding()]param([ValidateSet('Check','Prepare','Verify','Build','PackageLocal')][string]$Action='Check',[string]$BuildRoot='C:\tmp\dsh-official-desktop-build\work',[scriptblock]$CommandRunner,$Policy=(Get-DshOfficialDesktopBuildPolicy),[string]$Registry='https://registry.npmjs.org/')
 $check=Get-DshOfficialDesktopBuildCheck $BuildRoot $CommandRunner $Policy $Registry;if($Action-eq'Check'-or$check.status-ne'ready'){return $check};$root=$check.buildRoot;$source=Join-Path $root $Policy.sourceDirectory;$commands=[Collections.Generic.List[object]]::new();if($Action-eq'Verify'){if(-not(Test-Path $source)){throw 'official-source-not-prepared'};Assert-ManagedBuildTrees $root $Policy -IncludeTarget;$envRead=@{GIT_CONFIG_NOSYSTEM='1';GIT_CONFIG_GLOBAL='NUL'};Assert-NoReparseAncestor $source;Assert-OfficialSourceState $source $check.tools.git $Policy $envRead $CommandRunner|Out-Null;Assert-OfficialManifestFacts (Get-OfficialManifestFacts $source) $Policy;$receipts=@(Get-ChildItem (Join-Path $root $Policy.receiptDirectory) -Filter 'official-desktop-*.json' -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTimeUtc -Descending);if(-not$receipts.Count){throw 'verification-receipt-not-found'};$latest=$receipts[0];if(-not(Test-DshOfficialDesktopBuildReceipt $latest.FullName $source $Policy $check.tools.git $check.tools.nodeVersion $Policy.packageManager.Split('@')[-1] $CommandRunner)){throw 'command-order'};return [pscustomobject]@{action='verify';status='verified';sourceRoot=$source;receiptPath=$latest.FullName}}
 Initialize-OfficialBuildRoot $root $Policy;$environment=New-IsolatedEnvironment $root;if($Action-eq'Prepare'){if(Test-Path $source){throw 'prepare-refuses-existing-source'};$clone=Invoke-OfficialGit clone-official-tag $check.tools.git @('clone','--no-checkout','--filter=blob:none',$Policy.repository,$source) $root $environment $CommandRunner;$fetch=Invoke-OfficialGit fetch-official-tag $check.tools.git @('fetch','--no-tags','origin',('refs/tags/'+$Policy.tag+':refs/tags/'+$Policy.tag)) $source $environment $CommandRunner;$tag=(Invoke-OfficialGit resolve-fetched-tag $check.tools.git @('rev-parse',('refs/tags/'+$Policy.tag+'^{commit}')) $source $environment $CommandRunner).output[-1].Trim();if($tag-cne$Policy.commit){throw 'official-tag-commit-mismatch'};$checkout=Invoke-OfficialGit checkout-pinned-commit $check.tools.git @('checkout','--detach',$Policy.commit) $source $environment $CommandRunner}
 if(-not(Test-Path $source)){throw 'official-source-not-prepared'};Assert-ManagedBuildTrees $root $Policy -IncludeTarget;$state=Assert-OfficialSourceState $source $check.tools.git $Policy $environment $CommandRunner;Assert-OfficialManifestFacts (Get-OfficialManifestFacts $source) $Policy;$initialLock=$state.lockHash;$pnpmVersion=$Policy.packageManager.Split('@')[-1];$pnpm=Invoke-OfficialCheckedCommand pnpm-version $check.tools.corepack @(('pnpm@'+$pnpmVersion),'--version') $source $environment $CommandRunner;$commands.Add($pnpm.record);$actual=$pnpm.output[-1].Trim();if($actual-cne$pnpmVersion){throw 'pnpm-version-mismatch'};$install=Invoke-OfficialCheckedCommand frozen-install $check.tools.corepack (@(('pnpm@'+$pnpmVersion))+@($Policy.officialCommands.install)) $source $environment $CommandRunner;$commands.Add($install.record);Assert-OfficialSourceState $source $check.tools.git $Policy $environment $CommandRunner $initialLock|Out-Null;$routing=$null;$local=$null
 if($Action-cin@('Build','PackageLocal')){$routing=Invoke-PreparedDesktopBuild $source $root $Policy $check $environment $CommandRunner $check.registry $commands $initialLock}
 if($Action-eq'PackageLocal'){$target=Join-Path $source ($script:ArtifactRelativeRoot.Replace('/','\'));Assert-NoReparseAncestor $target;$artifacts=Join-Path $target 'artifacts';if(Test-Path $artifacts){Assert-NoReparseTree $artifacts;Remove-Item $artifacts -Recurse -Force};$overlay=New-LocalOverlay $root $source $Policy;$packageEnv=@{};foreach($key in $environment.Keys){$packageEnv[$key]=$environment[$key]};foreach($name in @('DSH_DESKTOP_TARGET','DSH_DESKTOP_TARGET_PLATFORM','DSH_DESKTOP_TARGET_ARCH','DSH_DESKTOP_WINDOWS_CER_FILE','DSH_DESKTOP_WINDOWS_SIGNTOOL','DSH_DESKTOP_WINDOWS_TOKEN_PIN','DSH_DESKTOP_WINDOWS_KEY_CONTAINER','WIN_CSC_LINK','WIN_CSC_KEY_PASSWORD','CSC_LINK','CSC_KEY_PASSWORD')){$packageEnv[$name]=$null};$packageEnv.DSH_DESKTOP_APP_ID=$Policy.localPackage.appId;$packageEnv.DSH_DESKTOP_AUTO_UPDATE_ENV='test';$packageEnv.DOWNLOAD_TEST_ORIGIN=$Policy.localPackage.testOrigin;$packageArgs=@(('pnpm@'+$pnpmVersion),'exec','electron-builder','--config',$overlay.path,'--win','--x64','--publish','never');$desktopRoot=Join-Path $source 'apps\desktop';Assert-NoReparseAncestor $desktopRoot;$package=Invoke-OfficialCheckedCommand local-electron-builder $check.tools.corepack $packageArgs $desktopRoot $packageEnv $CommandRunner;$commands.Add($package.record);Assert-OfficialSourceState $source $check.tools.git $Policy $environment $CommandRunner $initialLock|Out-Null;$local=Get-LocalPackageEvidence $source $root $Policy $overlay.path}
 $final=Assert-OfficialSourceState $source $check.tools.git $Policy $environment $CommandRunner $initialLock;$receipt=[pscustomobject][ordered]@{schemaVersion=1;action=$Action.ToLowerInvariant();status='complete';createdUtc=[DateTime]::UtcNow.ToString('o');source=[pscustomobject]@{repository=$Policy.repository;tag=$Policy.tag;commit=$final.identity.commit;tree=$final.identity.tree;clean=$final.identity.clean;lockfileSha256=$final.lockHash};tools=[pscustomobject]@{nodeVersion=$check.tools.nodeVersion;packageManager=$Policy.packageManager;pnpmVersion=$actual};commands=@($commands.ToArray());artifacts=@(Get-OfficialArtifactInventory $source);validation=[pscustomobject]@{launchedGui=$false;installedDesktop=$false;trackedSourceModified=(-not$final.identity.clean);isolatedDshHome=$environment.DSH_HOME};releaseBoundary=$(if($Action-eq'PackageLocal'){$Policy.localReleaseBoundary}else{$Policy.releaseBoundary})};if($routing){$receipt|Add-Member registryRouting $routing};if($local){$receipt|Add-Member localPackage $local};$receiptName="official-desktop-$($Action.ToLowerInvariant())-$([DateTime]::UtcNow.ToString('yyyyMMddTHHmmssfffffffZ')).json";$receiptPath=Join-Path (Join-Path $root $Policy.receiptDirectory) $receiptName;$written=Write-DshOfficialDesktopBuildReceipt $receipt $receiptPath;if(-not(Test-DshOfficialDesktopBuildReceipt $receiptPath $source $Policy $check.tools.git $check.tools.nodeVersion $pnpmVersion $CommandRunner)){throw("receipt-self-verification-failed:"+$script:LastReceiptValidationError)};[pscustomobject]@{action=$Action.ToLowerInvariant();status='complete';sourceRoot=$source;receiptPath=$receiptPath;receipt=$written}
}
Export-ModuleMember -Function Get-DshOfficialDesktopBuildPolicy,Test-DshOfficialDesktopBuildPolicy,Assert-DshOfficialDesktopBuildRoot,Assert-DshRegistry,Assert-PrepareSeedRegistrySource,Get-DshOfficialDesktopBuildCheck,Invoke-DshOfficialDesktopBuild,Write-DshOfficialDesktopBuildReceipt,Test-DshOfficialDesktopBuildReceipt
